// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://5.78.154.85:443' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MemberCreate
 */
export type MemberCreate = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type CreateFamilyFamilyPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Name
         */
        name: string;
    };
    url: '/family/';
};

export type CreateFamilyFamilyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFamilyFamilyPostError = CreateFamilyFamilyPostErrors[keyof CreateFamilyFamilyPostErrors];

export type CreateFamilyFamilyPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetFamilyFamilyFamilyIdGetData = {
    body?: never;
    path: {
        /**
         * Family Id
         */
        family_id: string;
    };
    query?: never;
    url: '/family/{family_id}';
};

export type GetFamilyFamilyFamilyIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFamilyFamilyFamilyIdGetError = GetFamilyFamilyFamilyIdGetErrors[keyof GetFamilyFamilyFamilyIdGetErrors];

export type GetFamilyFamilyFamilyIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetFamilyMembersFamilyGetMembersFamilyIdGetData = {
    body?: never;
    path: {
        /**
         * Family Id
         */
        family_id: string;
    };
    query?: never;
    url: '/family/get_members/{family_id}';
};

export type GetFamilyMembersFamilyGetMembersFamilyIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFamilyMembersFamilyGetMembersFamilyIdGetError = GetFamilyMembersFamilyGetMembersFamilyIdGetErrors[keyof GetFamilyMembersFamilyGetMembersFamilyIdGetErrors];

export type GetFamilyMembersFamilyGetMembersFamilyIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateMemberMembersRegisterPostData = {
    body: MemberCreate;
    path?: never;
    query?: never;
    url: '/members/register';
};

export type CreateMemberMembersRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMemberMembersRegisterPostError = CreateMemberMembersRegisterPostErrors[keyof CreateMemberMembersRegisterPostErrors];

export type CreateMemberMembersRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMemberMembersMemberIdGetData = {
    body?: never;
    path: {
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/members/{member_id}';
};

export type GetMemberMembersMemberIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMemberMembersMemberIdGetError = GetMemberMembersMemberIdGetErrors[keyof GetMemberMembersMemberIdGetErrors];

export type GetMemberMembersMemberIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddMemberMembersFamilyIdAddMemberIdPostData = {
    body?: never;
    path: {
        /**
         * Family Id
         */
        family_id: string;
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/members/{family_id}/add/{member_id}';
};

export type AddMemberMembersFamilyIdAddMemberIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMemberMembersFamilyIdAddMemberIdPostError = AddMemberMembersFamilyIdAddMemberIdPostErrors[keyof AddMemberMembersFamilyIdAddMemberIdPostErrors];

export type AddMemberMembersFamilyIdAddMemberIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMemberTransactionsMembersMemberIdTransactionsGetData = {
    body?: never;
    path: {
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/members/{member_id}/transactions';
};

export type GetMemberTransactionsMembersMemberIdTransactionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMemberTransactionsMembersMemberIdTransactionsGetError = GetMemberTransactionsMembersMemberIdTransactionsGetErrors[keyof GetMemberTransactionsMembersMemberIdTransactionsGetErrors];

export type GetMemberTransactionsMembersMemberIdTransactionsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetBorrowerTransactionsMembersMemberIdBorrowerTransactionsGetData = {
    body?: never;
    path: {
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/members/{member_id}/borrower_transactions';
};

export type GetBorrowerTransactionsMembersMemberIdBorrowerTransactionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBorrowerTransactionsMembersMemberIdBorrowerTransactionsGetError = GetBorrowerTransactionsMembersMemberIdBorrowerTransactionsGetErrors[keyof GetBorrowerTransactionsMembersMemberIdBorrowerTransactionsGetErrors];

export type GetBorrowerTransactionsMembersMemberIdBorrowerTransactionsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetBakraMembersThegoatBakraGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/members/thegoat/bakra';
};

export type GetBakraMembersThegoatBakraGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllBorrowersTransactionsMembersMemberIdGetAllBorrowersGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Member Id
         */
        member_id: string;
    };
    url: '/members/{member.id}/get_all_borrowers';
};

export type GetAllBorrowersTransactionsMembersMemberIdGetAllBorrowersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllBorrowersTransactionsMembersMemberIdGetAllBorrowersGetError = GetAllBorrowersTransactionsMembersMemberIdGetAllBorrowersGetErrors[keyof GetAllBorrowersTransactionsMembersMemberIdGetAllBorrowersGetErrors];

export type GetAllBorrowersTransactionsMembersMemberIdGetAllBorrowersGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMoneyRequestsMembersMemberIdMoneyRequestsGetData = {
    body?: never;
    path: {
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/members/{member_id}/money_requests';
};

export type GetMoneyRequestsMembersMemberIdMoneyRequestsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMoneyRequestsMembersMemberIdMoneyRequestsGetError = GetMoneyRequestsMembersMemberIdMoneyRequestsGetErrors[keyof GetMoneyRequestsMembersMemberIdMoneyRequestsGetErrors];

export type GetMoneyRequestsMembersMemberIdMoneyRequestsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RequestMoneyMembersFromIdRequestMoneyPostData = {
    body?: never;
    path: {
        /**
         * From Id
         */
        from_id: string;
    };
    query: {
        /**
         * To Id
         */
        to_id: string;
        /**
         * Amount
         */
        amount: number;
        /**
         * Description
         */
        description?: string | null;
    };
    url: '/members/{from_id}/request_money';
};

export type RequestMoneyMembersFromIdRequestMoneyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestMoneyMembersFromIdRequestMoneyPostError = RequestMoneyMembersFromIdRequestMoneyPostErrors[keyof RequestMoneyMembersFromIdRequestMoneyPostErrors];

export type RequestMoneyMembersFromIdRequestMoneyPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RespondToRequestMembersRespondRequestRequestIdPostData = {
    body?: never;
    path: {
        /**
         * Request Id
         */
        request_id: string;
    };
    query: {
        /**
         * Accept
         */
        accept: boolean;
    };
    url: '/members/respond_request/{request_id}';
};

export type RespondToRequestMembersRespondRequestRequestIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RespondToRequestMembersRespondRequestRequestIdPostError = RespondToRequestMembersRespondRequestRequestIdPostErrors[keyof RespondToRequestMembersRespondRequestRequestIdPostErrors];

export type RespondToRequestMembersRespondRequestRequestIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateTransactionTransactionsFamilyIdCreatePostData = {
    body?: never;
    path: {
        /**
         * Family Id
         */
        family_id: string;
    };
    query: {
        /**
         * From Id
         */
        from_id: string;
        /**
         * To Id
         */
        to_id: string;
        /**
         * Amount
         */
        amount: number;
        /**
         * Desc
         */
        desc?: string;
    };
    url: '/transactions/{family_id}/create';
};

export type CreateTransactionTransactionsFamilyIdCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTransactionTransactionsFamilyIdCreatePostError = CreateTransactionTransactionsFamilyIdCreatePostErrors[keyof CreateTransactionTransactionsFamilyIdCreatePostErrors];

export type CreateTransactionTransactionsFamilyIdCreatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMerchantsMerchantsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/merchants/';
};

export type GetMerchantsMerchantsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMerchantsMerchantsGetError = GetMerchantsMerchantsGetErrors[keyof GetMerchantsMerchantsGetErrors];

export type GetMerchantsMerchantsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateMerchantMerchantsCreatePostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Name
         */
        name: string;
        /**
         * Category
         */
        category: string;
        /**
         * City
         */
        city?: string;
        /**
         * State
         */
        state?: string;
    };
    url: '/merchants/create';
};

export type CreateMerchantMerchantsCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMerchantMerchantsCreatePostError = CreateMerchantMerchantsCreatePostErrors[keyof CreateMerchantMerchantsCreatePostErrors];

export type CreateMerchantMerchantsCreatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PayMerchantMerchantsPayPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Member Id
         */
        member_id: string;
        /**
         * Merchant Id
         */
        merchant_id: string;
        /**
         * Amount
         */
        amount: number;
        /**
         * Desc
         */
        desc?: string;
    };
    url: '/merchants/pay';
};

export type PayMerchantMerchantsPayPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PayMerchantMerchantsPayPostError = PayMerchantMerchantsPayPostErrors[keyof PayMerchantMerchantsPayPostErrors];

export type PayMerchantMerchantsPayPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
